<?php

namespace Advertproject\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderandProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderandProductRepository extends EntityRepository
{
}
