imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        webmaster: "%app_webmaster%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    #bundles:        [ APPlatformBundle ]
    #java: /usr/bin/java
    read_from: "%kernel.root_dir%/../../public_html"
    filters:
        cssrewrite: ~

        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:                  "%mailer_transport%"
    host:                       "%mailer_host%"
    username:                   "%mailer_user%"
    password:                   "%mailer_password%"
    spool:                      { type: memory }

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable:          true

#friend of symfony bunle configuration
fos_user:
    db_driver:                  orm
    firewall_name:              main
    user_class:                 Advertproject\UserBundle\Entity\User
    registration:
        form:
            type:               advertproject_userbundle_registration
        confirmation:
            enabled:            true
    use_username_form_type:     false
    from_email:
        address:                Andema@yafabhi.com
        sender_name:            Yafabhi Company
    registration:
        confirmation:
            from_email:
                address:        Andema@yafabhi.com
                sender_name:    Yafabhi Company
            template:           APUserBundle:Registration:email.txt.twig
    resetting:
        email:
            from_email:
                address:        Andema@yafabhi.com
                sender_name:    Yafabhi Company
            template:           email/password_resetting.email.twig
    service:
        mailer:                 fos_user.mailer.twig_swift


# GregwarImageBundle configuration
gregwar_image:
    throw_exception:            true
