<?php

namespace Advertproject\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    /*public function isFlood($ipAddress, $delay)
    {

        $qb = $this->createQueryBuilder('a')
            -> where("a.date < :delay")
            -> setParameter('delay', (new DateTime())->diff(new \DateTime('a.date'))->format('i'))
        ;
    }*/
}
