<?php

namespace Advertproject\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VotantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotantRepository extends EntityRepository
{
}
